export const TOGGLE_COLOR = 'TOGGLE_COLOR';
export const EXAMPLE_REQUEST_START = 'EXAMPLE_REQUEST_START';
export const EXAMPLE_REQUEST_DATA = 'EXAMPLE_REQUEST_DATA';


export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';


export const REQUEST_REGISTER= 'REQUEST_REGISTER';
export const RECEIVE_REGISTER = 'RECEIVE_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';


export const REQUEST_USER_REGISTER = 'REQUEST_LOGIN';
export const RECEIVE_USER_REGISTER = 'RECEIVE_LOGIN';

export const SET_AUTHED_USER = 'SET_AUTHED_USER'

export const RECEIVE_DATA_ADMIN_PANEL = "RECEIVE_DATA_ADMIN_PANEL";
